/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/drifterhov-1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/drifterhov-1.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="drifter_hull" position={[0.004, 0.156, 1.663]} rotation={[0, 0, -0.141]}>
          <mesh name="Torus002" geometry={nodes.Torus002.geometry} material={materials.trim} />
          <mesh name="Torus002_1" geometry={nodes.Torus002_1.geometry} material={materials.vents} />
          <mesh name="Torus002_2" geometry={nodes.Torus002_2.geometry} material={materials.lights} />
          <mesh name="Torus002_3" geometry={nodes.Torus002_3.geometry} material={materials['Car Paint']} />
          <mesh name="Torus002_4" geometry={nodes.Torus002_4.geometry} material={materials.interior} />
          <mesh name="Torus002_5" geometry={nodes.Torus002_5.geometry} material={materials['black paint']} />
          <mesh name="Torus002_6" geometry={nodes.Torus002_6.geometry} material={materials.floor} />
          <mesh name="Torus002_7" geometry={nodes.Torus002_7.geometry} material={materials.brake} />
          <mesh name="Torus002_8" geometry={nodes.Torus002_8.geometry} material={materials.cam} />
        </group>
        <mesh name="Torus001" geometry={nodes.Torus001.geometry} material={materials.rubber} position={[0.997, 0.201, 1.591]} rotation={[0, 0, -0.154]} />
        <mesh name="Torus003" geometry={nodes.Torus003.geometry} material={materials.steel} position={[0.997, 0.201, 1.591]} rotation={[0, 0, -0.154]} />
        <mesh name="Torus004" geometry={nodes.Torus004.geometry} material={materials.rubber} position={[0.993, 0.201, -1.446]} rotation={[0, 0, -0.154]} />
        <mesh name="Torus005" geometry={nodes.Torus005.geometry} material={materials.steel} position={[0.993, 0.201, -1.446]} rotation={[0, 0, -0.154]} />
        <group name="roof" position={[0.005, 1.011, 0.1]} rotation={[0, 0, -0.141]}>
          <mesh name="Torus009" geometry={nodes.Torus009.geometry} material={materials['Car Paint']} />
          <mesh name="Torus009_1" geometry={nodes.Torus009_1.geometry} material={materials.glaze} />
          <mesh name="Torus009_2" geometry={nodes.Torus009_2.geometry} material={materials.trim} />
          <mesh name="Torus009_3" geometry={nodes.Torus009_3.geometry} material={materials.cam} />
          <mesh name="Torus009_4" geometry={nodes.Torus009_4.geometry} material={materials.steel} />
        </group>
        <group name="Plane001" position={[0.503, 0.03, -0.736]} rotation={[Math.PI, 0, Math.PI]} scale={[0.043, 1, 0.207]}>
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials['Car Paint']} />
          <mesh name="Plane001_2" geometry={nodes.Plane001_2.geometry} material={materials.rubber} />
          <mesh name="Plane001_3" geometry={nodes.Plane001_3.geometry} material={materials.steel} />
        </group>
        <mesh name="Text" geometry={nodes.Text.geometry} material={materials.steel} position={[0.182, 1.045, -0.605]} rotation={[1.589, 0.537, -1.716]} scale={0.079} />
        <group name="seat_cushions" position={[0.007, 0.772, 0.099]} rotation={[Math.PI / 2, 0, 0]} scale={[0.59, 0.452, 0.452]}>
          <mesh name="seat_cushions_1" geometry={nodes.seat_cushions_1.geometry} material={materials['seats mat']} />
          <mesh name="seat_cushions_2" geometry={nodes.seat_cushions_2.geometry} material={materials.Ch48_body1} />
          <mesh name="seat_cushions_3" geometry={nodes.seat_cushions_3.geometry} material={materials.Ch48_body} />
          <mesh name="seat_cushions_4" geometry={nodes.seat_cushions_4.geometry} material={materials.Ch48_hair} />
        </group>
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.struct} position={[-0.222, 0.492, 0.35]} scale={[0.01, 0.032, 0.699]} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.struct} position={[0.229, 0.492, 0.35]} scale={[0.01, 0.032, 0.699]} />
        <group name="Cube003" position={[0.004, 0.772, 0.691]} scale={[0.181, 0.08, 0.014]}>
          <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials.dashboard} />
          <mesh name="Cube004_1" geometry={nodes.Cube004_1.geometry} material={materials.screen} />
          <mesh name="Cube004_2" geometry={nodes.Cube004_2.geometry} material={materials['side screen 2']} />
        </group>
        <group name="BezierCurve" position={[0.094, 0.829, 0.419]} rotation={[-0.634, 0, -Math.PI / 2]} scale={[0.125, 1, 0.321]}>
          <mesh name="BezierCurve_1" geometry={nodes.BezierCurve_1.geometry} material={materials.steel} />
          <mesh name="BezierCurve_2" geometry={nodes.BezierCurve_2.geometry} material={materials['handle bars']} />
        </group>
        <group name="BezierCurve001" position={[-0.079, 0.829, 0.419]} rotation={[-0.634, 0, -Math.PI / 2]} scale={[0.125, 1, 0.321]}>
          <mesh name="BezierCurve001_1" geometry={nodes.BezierCurve001_1.geometry} material={materials.steel} />
          <mesh name="BezierCurve001_2" geometry={nodes.BezierCurve001_2.geometry} material={materials['handle bars']} />
        </group>
        <mesh name="Torus006" geometry={nodes.Torus006.geometry} material={materials.steel} position={[0.993, 0.201, -1.446]} rotation={[0, 0, -0.154]} />
        <mesh name="Torus007" geometry={nodes.Torus007.geometry} material={materials.steel} position={[0.997, 0.201, 1.591]} rotation={[0, 0, -0.154]} />
        <mesh name="Text001" geometry={nodes.Text001.geometry} material={materials.steel} position={[0.139, 1.115, -0.605]} rotation={[1.589, 0.537, -1.716]} scale={0.057} />
      </group>
    </group>
  )
}

useGLTF.preload('/drifterhov-1.glb')
