/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/iphone_13_concept.glb 
Author: DatSketch (https://sketchfab.com/DatSketch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-13-concept-d064458166e146779cb7bf802d2c0056
Title: iPhone 13 Concept
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/iphone_13_concept.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.IPHONE13_Frame1_0.geometry} material={materials.Frame1} />
        <mesh geometry={nodes.IPHONE13_SpeakerAndMic1_0.geometry} material={materials.SpeakerAndMic1} />
        <mesh geometry={nodes.IPHONE13_gray2_0.geometry} material={materials.gray2} />
        <mesh geometry={nodes.IPHONE13_AntennaStrip_0.geometry} material={materials.AntennaStrip} />
        <mesh geometry={nodes.Body_Back1_0.geometry} material={materials.Back1} />
        <mesh geometry={nodes.Body_Bezel1_0.geometry} material={materials.Bezel1} />
        <mesh geometry={nodes.Body_SpeakerAndMic1_0.geometry} material={materials.SpeakerAndMic1} />
        <mesh geometry={nodes.Body_CameraGlass1_0.geometry} material={materials.CameraGlass1} />
        <mesh geometry={nodes.Body_Logo1_0.geometry} material={materials.Logo1} />
        <mesh geometry={nodes.FrontCamLens_Lens1_0.geometry} material={materials.Lens1} />
        <mesh geometry={nodes.Screen_Screen1_0.geometry} material={materials.Screen1} />
        <mesh geometry={nodes.CamModule_CameraModule1_0.geometry} material={materials.CameraModule1} />
        <mesh geometry={nodes.CamModule_CameraMGlass1_0.geometry} material={materials['CameraM.Glass1']} />
        <mesh geometry={nodes['Camera_Camera(1)_0'].geometry} material={materials.Camera1} />
        <mesh geometry={nodes.Camera_Chrome1_0.geometry} material={materials.Chrome1} />
        <mesh geometry={nodes.Camera_CameraBlack1_0.geometry} material={materials.CameraBlack1} />
        <mesh geometry={nodes.Camera_CameraGray1_0.geometry} material={materials.CameraGray1} />
        <mesh geometry={nodes.Camera_CameraGlass1_0.geometry} material={materials.CameraGlass1} />
        <mesh geometry={nodes.Flash_Chrome2_0.geometry} material={materials.Chrome2} />
        <mesh geometry={nodes.Flash_Flash1_0.geometry} material={materials.Flash1} />
        <mesh geometry={nodes.Mic_Chrome2_0.geometry} material={materials.Chrome2} />
        <mesh geometry={nodes.Mic_SpeakerAndMic1_0.geometry} material={materials.SpeakerAndMic1} />
        <mesh geometry={nodes.Lens1_Lens1_0.geometry} material={materials.Lens1} />
        <mesh geometry={nodes.Lens2_Lens1_0.geometry} material={materials.Lens1} />
        <mesh geometry={nodes.PowerButton_Frame1_0.geometry} material={materials.Frame1} />
        <mesh geometry={nodes.VolumeButton_Frame1_0.geometry} material={materials.Frame1} />
        <mesh geometry={nodes.MuteButton_Frame1_0.geometry} material={materials.Frame1} />
        <mesh geometry={nodes.SIMTray_Frame1_0.geometry} material={materials.Frame1} />
        <mesh geometry={nodes.SIMTray_Chrome1_0.geometry} material={materials.Chrome1} />
        <mesh geometry={nodes.Port_LPort_0.geometry} material={materials['L.Port']} />
        <mesh geometry={nodes.Port_Frame1_0.geometry} material={materials.Frame1} />
      </group>
    </group>
  )
}

useGLTF.preload('/iphone_13_concept.glb')
